name: Update badges

on:
  schedule:
    # Runs at 2am UTC daily
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CREDLY_USER: "hassansardarnaveed"
          # This ensures it hits the exact section in your README
          LABEL_START: ""
          LABEL_END: ""
          NUMBER_LAST_BADGES: 0
